version: "3.7"
services:
  tomcat:
    build:
      context: .
      dockerfile: tomcat/Dockerfile
    links:
      - postgres
    ports:
      - '8085:8085'
    working_dir: /opt/tomcat
  maven:
    image: maven
    working_dir: /usr/src/mymaven
    command: mvn clean tomcat7:redeploy
    links:
      - tomcat
    volumes:
      - ./:/usr/src/mymaven
      - maven-repo:/root/.m2
      - ./maven/config/settings.xml:/usr/share/maven/conf/settings.xml
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
    ports:
      - '5432:5432'
    volumes:
      - tomcat-postgres:/var/lib/postgresql/data
volumes:
  maven-repo:
  tomcat-postgres:
